"""add_login_method_field_to_user_table

Revision ID: 6f93487676ef
Revises: 68c5f4c9c364
Create Date: 2025-03-24 12:35:58.119674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f93487676ef'
down_revision: Union[str, None] = '68c5f4c9c364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_method', sa.String(length=20), server_default='local', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_method')
    # ### end Alembic commands ###
