"""add_test_migration

Revision ID: f9691c169278
Revises: 658ea29ec6d8
Create Date: 2025-03-13 23:42:19.186816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9691c169278'
down_revision: Union[str, None] = '658ea29ec6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('test', sa.String(), nullable=False))
    op.alter_column('books', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('comments', sa.Column('test', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'test')
    op.alter_column('books', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('books', 'test')
    # ### end Alembic commands ###
